#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'apt'
# cookbook 'nodejs'
# cookbook 'memcached'
# cookbook 'logrotate'
# cookbook 'mysql'

# cookbook 'ohai'
# cookbook 'openssl'
# cookbook 'sudo'


cookbook 'ruby_build'
cookbook 'rbenv', :github => "fnichol/chef-rbenv"

# cookbook "redis", :github =>"ctrabold/chef-redis"
# cookbook 'postgresql', :github => "phlipper/chef-postgresql"
# cookbook 'users', :github => "arrowcircle/chef-users"
# cookbook 'nginx', :github => "arrowcircle/chef-nginx"
# cookbook 'puma'
# cookbook 'unicorn'

cookbook 'rails-stack', :github => "happyFish/chef-rails-stack"